name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract repository/service name
        id: extract-name
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Extract current version from package.json
        id: get-version
        run: |
          # Extract version from package.json and remove -snapshot if present
          version=$(node -p "require('./package.json').version.replace('-snapshot', '')")
          echo "VERSION=$version" >> $GITHUB_ENV  

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dev.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/privatediregistry:${{ env.REPO_NAME }}-${{ env.VERSION }}

      - name: Create GitHub Tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            # Create a tag for the new release version
            git tag "v${{ env.VERSION }}"
            git push origin --tags
          fi